### ISSUE TITLE
Blog Post add any ChildNodes to Main ContentCollection

### ISSUE THREAD

**Issue by bbtimx** [patriceckhart/NeosRulez.Blog#2]
Why it is not possible or allowed to add any ChildNodes to the Main ContentCollection?

Most of the time, simple Text Node is not enough for a blog post.

**Comment by patriceckhart** [comment]
It is allowed. Only `NeosRulez.Blog:Content.BlogPostComment` is not allowed. Look at the `NodeTypes.Document.BlogPost.yaml`, from line 139 you can see which constraints are defined. You can also override this in your site package and explicitly allow or disallow which of your NodeTypes.

**Comment by bbtimx** [comment]
Found my mistake ...

Forgott to copy `{props.main}` from `Resources/Private/Fusion/Component/BlogPost/BlogPost.fusion` to my overwrite.
